version: "3.2"
services:
  app:
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST} 
      API_URL: ${API_URL}
      API_KEY: ${API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo/mongo-volume:/data/db
    expose:
      - 27017
